### ISSUE TITLE
Consider reversing metaphor so unlock means you can edit

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#119]
There is an existing metaphor that when apps show things as locked you cannot edit, while the app does the reverse. For example on mac, this indicates you cannot edit (see bottom):

![image](https://user-images.githubusercontent.com/81305/131723751-cadaec2d-e6c2-48b6-8336-107a993d82f8.png)

Consider using a locked icon if you cannot edit it, and convert to unlocked when you can edit.

**Comment by zachmullen** [comment]
There's a third state to consider how to visualize, which is a lock held by a user other than yourself.

**Comment by jeffbaumes** [comment]
My suggestion would be:

* Unlocked icon (active/black): Lock held by you (it's unlocked to you and you are able to edit, clicking will release the lock and make it read-only).
* Locked icon (active/black): Lock held by no one (you can click it to unlock it and edit)
* Locked icon (inactive/gray): Lock held by other user (it's locked to you and you aren't able to click it to unclick it)

**Comment by jeffbaumes** [comment]
@faiza-a will be reaching out to @annehaley for a usability review

**Comment by aashish24** [comment]
some other suggestion in the meeting today: 

1. instead of lock / unlock show user icon that has acquired the experiment 
2. initially just gray or some other color to show it is open for anyone to review (something that @zachmullen mentioned, hoping I captured it correctly)

**Comment by faiza-a** [comment]
@aashish24 Thanks for sharing these ideas. I just spoke to @annehaley and will see what options we could come up for this. i will probably have some quick mockups to share ideas next week. including the gray colored idea you mentioned above

**Comment by aashish24** [comment]
> @aashish24 Thanks for sharing these ideas. I just spoke to @annehaley and will see what options we could come up for this. i will probably have some quick mockups to share ideas next week. including the gray colored idea you mentioned above

Awesome. Looking forward to the mockups @faiza-a

**Comment by annehaley** [comment]
Closing in favor of #173
