### ISSUE TITLE
Set up Git LFS for NN model tracking

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#124]

**Comment by dzenanz** [comment]
Currently the network weights are around 100KB big, so I am not sure whether we want the extra complication of `git-lfs`. If these files start getting bigger we could add `git-lfs` later. @zachmullen what do you think?

**Comment by zachmullen** [comment]
That is a lot smaller than I am used to. Still, especially if we anticipate more models, I think we should just go ahead and set up git-lfs. I'll look into it.

**Comment by dzenanz** [comment]
I can do it. It is not a problem, just making sure that we want it.
