### ISSUE TITLE
NN integration: DevOps to get models built into images

### ISSUE THREAD

**Issue by zachmullen** [OpenImaging/miqa#126]

**Comment by annehaley** [comment]
@zachmullen Can I ask for clarification on this task? I know we discussed it in last weeks meeting, and I think this is referring to the idea that the user who imports data should be able to select the NN model to use on the set. Is this correct?

**Comment by zachmullen** [comment]
The task here is just to get the model files built in to our docker images so that they can be run as part of our deployment. @dzenanz can provide the model files, we'll need to have a directory in the repo that is gitignored where they can be placed, and then the Dockerfile can COPY the files into the place where the task will look for them. We can have a meeting if you need additional guidance.

**Comment by annehaley** [comment]
Ah, I understand. Glad I  asked because I completely misinterpreted. I might ask for your help on this later, but I think I can get started on it.

**Comment by dzenanz** [comment]
For now, you can use the `.pth` files in learning directory as 5 distinct models.
