### ISSUE TITLE
NN integration: Django models for NN outputs, linked to scan

### ISSUE THREAD

**Issue by zachmullen** [OpenImaging/miqa#127]
The NN is run on a scan, not on an image.

Outputs from the NN:
* a grade [0,10], which indicates the overall quality of the scan. 
* 10 classification probabilities [0,1]. These should be rendered in the UI as tags if they are above a cutoff.

**Comment by dzenanz** [comment]
Outputs are correct. The confidence interval for overall quality is 0-10, but we can rescale it to 0-1 if that is advantageous.

**Comment by zachmullen** [comment]
Thanks, I updated the description.

**Comment by jeffbaumes** [comment]
I feel "confidence interval" is not the right label for the first number (that term means something else statistically and this is not an interval it's a single number), maybe it should be "overall quality".

**Comment by dzenanz** [comment]
I renamed it to "grade".
