### ISSUE TITLE
NN integration: celery task that runs on ingest

### ISSUE THREAD

**Issue by zachmullen** [OpenImaging/miqa#128]

**Comment by annehaley** [comment]
@zachmullen is there any use case where a data import should not start an evaluation? If not, this might not need to be queued as a separate celery task. It could just be part of the import_data task.

**Comment by zachmullen** [comment]
Good call, I wasn't sure of the context this was running. If it's not inside a web request context, we don't need to send it to celery.

**Comment by curtislisle** [comment]
I believe wsers will want to choose which model should be run when data is imported. Or we could have some configurable defaults.  For example, we will want to have different quality models at least for each image modality (T1, T2, CT, etc.).  Is it worth adding  a Django model to act as our default "look up table" for which model is run depending on the image input parameters?  or is there a simpler way?

**Comment by annehaley** [comment]
Yes, this is absolutely doable. Right now the Session object has a new field called `selected_nn_model` which points to an instance of `NNModel` (though it could be changed to point to more than one, if that functionality is desired). This selection will have a default, but can be changed upon the creation of the Session before the import is done.

**Comment by curtislisle** [comment]
Let's discuss in our upcoming meeting.  We might want to add attributes to the Django models so an "EvaluationModel" knows which types of scans it can successfully process.  This would allow us to run appropriate models on scans within a session if some scans need one type of model and other scans need a different type of model.  For example, a session with T1 and T2 MRI images.  Then the "session" object could be given a list of the two models to correspond with these two scan types.

**Comment by curtislisle** [comment]
We discussed having an enumerated list of EvaluationModels.  One example for a procedural model used to generate some quality metrics on MRI scans is **MRQy**, available here: https://github.com/ccipd/MRQy.  When I looked at the code a few months ago, this repository had started using `pipenv` for installation, which I didn't like.  I did a git checkout of the version before the conversion to pipenv and I found it pretty easy to integrate.

**Comment by curtislisle** [comment]
MRIQC: https://github.com/poldracklab/mriqc; is the best known MR quality control system.  MRIQC may be better known and respected by MRI scientists, but I found it hard to integrate and very slow to run, so I migrated to using MRQy for our early experiments.  MRIQC is mentioned here for this discusison just because it is well-known.
