### ISSUE TITLE
Investigate XNAT API availability

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#130]
Explore options for integrating with XNAT.  Should we reimplement some of what Jim has done in this scripts, here: 

https://github.com/sibis-platform/ncanda-data-integration/blob/master/scripts/xnat/check_new_sessions. 

or could systems built to be adjacent to XNAT, such as DAX:
([Distributed Automation for XNAT](https://dax.readthedocs.io/en/stable), be helpful?

**Comment by curtislisle** [comment]
DAX is the system from Vanderbilt that I was discussing today.  Vandy used/uses XNAT to support 300+ projects simultaneously and found the XNAT API to be too slow.  according to its documentation, DAX accesses the database underneath an XNAT insance and offers download/upload and other tools for higher throughput.
