### ISSUE TITLE
Investigate merge with SQAN project from Indiana

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#134]
During the Slicer Project Week, a group from Indiana University presented a system called SQAN (pronounced “scan”) that performs automated quality testing of medical images.   Currently our projects are very complimentary and it might make some sense to collaborate or incorporate their work into MIQA.  

- They currently do detailed examination of DICOM header tags, which is something we don’t do.   We might want to incorporate some of their DICOM analysis.  
- The SQAN team mentioned wanting to integrate with XNAT in the future.  Maybe this is something we can look at together?  
- The SQAN User interface seems well implemented (in Vue.js completely in Javascript) to handle some of the issues of distributed, collaborative sites.   

This issue is a reminder to investigate possibly incorporating some parts of SQAN into MiQA and also consider if it is beneficial to collaborate with the team in Indiana as well.

**Comment by zachmullen** [comment]
Looks like SQAN is all node.js. But we have good experience with pydicom, so porting their DICOM header validation might be straightforward.

**Comment by curtislisle** [comment]
Aha.  This issue was moved.  For a moment, I wondered how I accidentally created this issue while visiting the old issue this morning :-).   I agree with @zachmullen that some of the pydicom header validation might be useful to add at some point, I think this is lower priority than the visual anomalies, but DICOM compliance is important and is completely unaddressed by the current MIQA.  I believe the other parts of SQAN are not useful for us. I was particularly looking for task/issue management and didn't see evidence of this in their demonstration.

**Comment by dzenanz** [comment]
When creating #135, I remembered Curt brought up something similar before. I searched for it, and when I saw it was in the old repo I transferred it.
