### ISSUE TITLE
Find appropriate conference for MIQA paper

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#143]

**Comment by dzenanz** [comment]
[MIDL22](https://2022.midl.io/dates.html) suits us time-wise:
 * Full paper submission deadline 17 December 2021
 * Short paper submission deadline 22 April 2022

Considering they have a two tier system (full and short papers), we should be able to get something accepted.

**Comment by aashish24** [comment]
Should we go for full paper or short? Also, is this conference okay with heavy on technical content?

**Comment by dzenanz** [comment]
I guess we should decide mid-November whether we want to try a full paper or only a short one. Judging by the [last year's papers](https://openreview.net/group?id=MIDL.io/2021/Conference), the conference is totally OK with technical-heavy papers.

**Comment by aashish24** [comment]
Sounds good could you start a template so that we can star working on putting some text or is that too soon?

**Comment by dzenanz** [comment]
I think it is too soon.
