### ISSUE TITLE
CI test fails for master

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#157]
Master consistently fails its CI tests after a PR, even if the PR code passed its tests. Master has an additional CI step to build the docker image and push to miqa/django:latest, but fails to do so every time. 

The following error is reached on every master CI test:
```
...
#10 pushing miqa/django:latest with docker
#10 pushing layer 5f70bf18a086
#10 pushing layer 847c756d1f2b
#10 pushing layer 8d2bb717d86b
#10 pushing layer eb8408126da6
#10 pushing layer d82f4c466b47
#10 pushing layer 5aa75f4e55e7 0.1s
#10 pushing layer 74d6903a940b 0.1s
#10 pushing layer 2f9c2b8e82bd 0.1s
#10 pushing layer ba5a5fe43301 0.1s
#10 pushing layer 5f70bf18a086 0.7s done
#10 pushing layer 847c756d1f2b 0.7s done
#10 pushing layer 8d2bb717d86b 0.7s done
#10 pushing layer eb8408126da6 0.7s done
#10 pushing layer d82f4c466b47 0.7s done
#10 pushing layer 5aa75f4e55e7 0.8s done
#10 pushing layer 74d6903a940b 0.8s done
#10 pushing layer 2f9c2b8e82bd 0.8s done
#10 pushing layer ba5a5fe43301 0.8s done
#10 ERROR: denied: requested access to the resource is denied
```

Can this access be granted to the CI runner or should this step be removed from the process?

**Comment by zachmullen** [comment]
Assigned to @dchiquito since he initially set this up.

**Comment by dchiquito** [comment]
Crazy, I have no recollection of why I did that. I thought it was a holdover from the Girder 3 app. Maybe this was speculative stuff from when I was setting up the production deployment.

I'm going to remove this CI step and the `Dockerfile` that it attempts to build, since neither are used anywhere.
