### ISSUE TITLE
Revisit window level control UI for usability

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#161]
In a discussion today, there were ideas on how to improve the window level controls:

* Do the min/max of the sliders need to be editable, or should they be static on the data-derived min and max values? It was brought up that finer grained control may be needed where there are varied ranges across timesteps in a scan
* If we allow it editing of the range, what should the UI be? Some ideas:
  * Keep current manually editable min/max value text boxes
  * Show histogram for context to see where relevant values are for the currently shown image
  * Perhaps have buttons for "reset range to current image" and "reset range to full scan"

**Comment by annehaley** [comment]
Closing in favor of #173
