### ISSUE TITLE
Crosshair to show the other slice locations

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#170]
This is something came from Jim and he mentioned that all other viewers have it. 

@annehaley fyi

**Comment by annehaley** [comment]
Is this something that would need to be added to the VTK code? If not, we can add it on top. If so, should we consider making a plugin for VTK?

**Comment by dzenanz** [comment]
Jim explicitly mentioned it is lower priority. It might be easy-ish to do, but I think it should be done in `vtk.js`. You might want to ask Forrest about it.

**Comment by curtislisle** [comment]
This is done beautifully in itk snap, in my opinion, if you are looking for an example.
