### ISSUE TITLE
Allow references to remote files in an import csv

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#179]
Right now, an import csv must use absolute paths referencing files that already exist on the server machine, and that's what the `raw_path` field on an Image/Frame must contain. We will eventually want to replace this with any kind of URI.

**Comment by annehaley** [comment]
@curtislisle @zachmullen You two worked to reference s3 paths in the import file, right? Was it successful? If so, could you describe the steps you took so I can include it in the documentation and resolve this issue?

**Comment by zachmullen** [comment]
Yes, it was. Are you looking for user documentation on how to import from S3 paths, or something else?

**Comment by annehaley** [comment]
Specifically for importing those files via a csv or json; what did the import file need to contain and was any additional setup required?

**Comment by zachmullen** [comment]
Oh, sure. The import path must be of the form `s3://bucket_name/key_name.csv`, and then all of the file references inside of the CSV file must also be absolute S3 paths of the same form. Exporting to S3 is not currently supported; if it works, it's by accident.
