### ISSUE TITLE
Improve screenshot options and capturing 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#18]
- [ ] Enable a option (via admin interface) to set the height of the screenshot. Width of the screenshot will be computed from the aspect ratio. 
- [ ] The screenshot needs to capture only the data outline (without the background). Hence the size needs correspond to the data bounds and not to the viewport. Below is the message from Jim from Stanford. 
- [ ] The screen shot issue is somewhat fixed.  512x512 max proportions seems fine.  The problem we seem is that there is too much black, and the actual MRI image is very small and low resolution in comparison to the image size embedded in the email.
![Image sample from 4K browser](https://user-images.githubusercontent.com/588760/119390657-38399400-bc82-11eb-9db2-09d0997a2439.png)

The browser size and host resolution seems to also still play a variable, as when I took snapshots using my iPad, the scan better fills the 512x512 box, however the image resolution seems low the size.
![Image Sample from iPad Pro 12.9"](https://user-images.githubusercontent.com/588760/119389217-28b94b80-bc80-11eb-872d-c746bd4361c9.png)

**Comment by aashish24** [comment]
Follow on of #4

**Comment by jimklo** [comment]
@aashish24 regarding:

> Enable a option (via admin interface) to set the width of the screenshot. Height of the screenshot will be computed from the aspect ratio.

I would suggest supplying both a height and a width constraints.  It should be possible to compute which way to scale based upon the the aspect ratio of the image. 

ie:
* 4:3 aspect ratio ( > 1 ) would use width constraint
* 3:4 aspect ratio ( < 1 ) would use height constraint

This way we might want to set height constraint to 512, but width constraint to 800.

If you only want to set only one, choose height in lieu of width. Vertical space for most viewers is more limited than horizontal,  Constraining the width could cause portrait oriented scan to resize much taller than desired, however a landscape image might be much smaller than desired. 

For Kilian's perspective, when reviewing screenshots via email, the vertical space is most important as he needs to be able to see the notes with the image without vertical scrolling. So in this case of a 4:3 viewport... having an image with a fixed height of 512 px (resulting in 683 px wide)  would be preferred over fixing the width at 512, and ending up with an image thats 384 px tall.

**Comment by aashish24** [comment]
Thanks, these are excellent thoughts. I think from the simplicity point of view, I am in favor of just one so height would be the best pick as per your comment. Also, please note that I am hoping that we can get rid of most of the background space which will require camera to change its parameters. Would that be okay?

**Comment by aashish24** [comment]
I have sent an email to the vtk.js developers team to this end and now waiting for their evaluation.
