### ISSUE TITLE
Update XNAT CSV generation to new format

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#186]
https://github.com/OpenImaging/miqa/pull/181#issuecomment-937292645
>This change to the CSV format would disrupt the current workflow used to import data from XNAT. To avoid that, we could add an argument to https://github.com/sibis-platform/ncanda-data-integration/blob/master/scripts/xnat/check_new_sessions that makes it generate a "new" CSV. That way they can continue to use that script for the Girder 3 deployment as long as that continues to be supported, while still supporting the new deployment.
>
>That doesn't need to be done right now, but eventually I think we should take the convert_miqa_import_csv_format.py script and add it directly to check_new_sessions.

**Comment by annehaley** [comment]
Resolved by https://github.com/sibis-platform/ncanda-data-integration/pull/427
