### ISSUE TITLE
Logout button doesn't work after session timeout

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#189]
I noticed in development that after some time, API requests begin to fail because the user's session timed out. When this happens, the logout button breaks, and no longer redirects the user to the login window.

I think the problem is with the API client `logout` method:
```
  async logout() {
    await apiClient.post('/logout/', undefined, { withCredentials: true });
    await oauthClient.logout();
  },
```
If the `apiClient.post('/logout/', ...)` returns a 401 Unauthorized, the `logout()` function throws an exception and never calls `oauthClient.logout()`, which would redirect the user to the login form.

**Comment by annehaley** [comment]
Resolved with #356
