### ISSUE TITLE
Handle xnat display size limits 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#191]
Currently XNAT has very short length for displaying the notes in the UI. Jim will send the information to us 15 characters.  What it stores and what it displays have different length. 

The format is something like this:
[Reviewers Initial] Short message (total 15 char long)

**Comment by annehaley** [comment]
We decided that the MIQA design is to include verbose information in the export file. It will be the responsibility of the NCANDA ingest script to parse that verbose information and condense it to fit into the XNAT db column.
