### ISSUE TITLE
Implement task work queue (dashboard)

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#192]

**Comment by annehaley** [comment]
Oh, I might have misunderstood. How are we considering the use case for reviewers passing scans back and forth?

**Comment by annehaley** [comment]
Ok, that sounds good to me.

**Comment by aashish24** [comment]
Relates to #229

**Comment by annehaley** [comment]
@faiza-a made this mockup for this issue: https://www.figma.com/file/94SRq5PLgJj5qn8Ho6mwGW/Dashboard-and-create-project-screens?node-id=0%3A1 and I will begin implementing this version.

**Comment by aashish24** [comment]
> @faiza-a made this mockup for this issue: https://www.figma.com/file/94SRq5PLgJj5qn8Ho6mwGW/Dashboard-and-create-project-screens?node-id=0%3A1 and I will begin implementing this version.

Looking good, once implemented, we could touch up few things if needed.
