### ISSUE TITLE
Defines roles in MIQA (similar to XNAT) 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#204]
* Owners - owns a project
* Members - can review a experiment scans
* Collaborators - can only view and read notes

**Comment by annehaley** [comment]
Based on what we learned, it seems that we want a user to have one universal role: they are either a Standard User or a Superuser. 
- A superuser can create, edit, and delete projects. This means they can add/remove any other users to a project and define their permissions on that project.
- All users (super or not) have project-specific roles. This means that you can be a first-tier reviewer on Project A and a second-tier reviewer on Project B. 
- When configuring a project, the superuser can define user groups that exist on the project. The default groups are Tier 1 Reviewers, Tier 2 Reviewers, and Collaborators. When a superuser edits the project, they can change the roles assigned to members.
- Superusers and Standard Users have different views in the Projects tab. Both will see the list of scans and the list of users for that Project, but only superusers will see an editable version. In the sidebar, superusers will have buttons to create a new project and to delete a project. In the details for a single project, superusers will have an editable version of the users list (to add, remove, and change permissions for users) and a section of options for configuration.
- A superuser will have the following abilities among a Project's configuration options: 
    - Editing the import path and export path
    - Performing an import or export (or should this be available to all users?)
    - (Advanced) Editing the groups for that project
    - (Advanced) Editing the flow and states for a single scan in that project

- The scans that come up on a user's dashboard for their review are organized by project and are therefore filtered according to the role they have on that project. (i.e. if I am a first-tier reviewer on Project A and a second-tier reviewer on Project B, then what I see on my dashboard are the scans from Project A in need of a first review and the scans from Project B that have received a first review and need a second.)

**Comment by jeffbaumes** [comment]
> (Advanced) Editing the flow and states for a single scan in that project

These items add quite a bit to the scope of this work (i.e. 2-5x complexity). As I see it we could implement this in a few different levels:

1. Hard code the groups and workflow into the app where workflow changes require code changes
2. Encode specific workflows into a configuration that resides on the server (i.e. there is no way to edit them from the UI). This could be JSON/YAML/etc. that defines one or more workflow "types", one of which would be called "two-stage review". All the admin could do is select one of the predefined types when creating a project.
3. Enable UI for fully creating and editing the workflow in the admin web UI. Workflow information/roles/rules would need to be stored in the database at runtime.

I'd advocate for no higher than level 2, where UI is not involved for workflow editing. If we do level 3, we are basically creating a full workflow system much like Monday.com or other enterprise tools and I fear the scope will explode. If we wanted to add UI to create/edit workflow types, we could always add that later on.

Others please chime in, maybe it's an easier problem than it appears to me.

**Comment by annehaley** [comment]
I agree that we should stay at level 2, where we consider a more complex design but do not implement it. We just know that our approach should be more flexible for future features like workflow editing.

**Comment by dzenanz** [comment]
Stay at level 1 for now. We could do level 2 later, if it makes sense. Level 3 would add so much complexity, it makes no sense to me. Unless I am also mistaking the hard it is 😄

**Comment by annehaley** [comment]
![MIQA Project User Groups](https://user-images.githubusercontent.com/44912689/140407989-a2aebc7b-bca0-4861-aadc-662edaed7157.png)
This model is expandable, but we can hard-code it to only Tier 1 Reviewers and Tier 2 Reviewers for now. @curtislisle mentioned that cyclical review is not a use case for Stanford, but it seems to be the norm for Kilian. Perhaps a boolean `cyclical_review` option on the Project could handle that logic?

**Comment by annehaley** [comment]
![MIQA Project User Groups](https://user-images.githubusercontent.com/44912689/140415424-17d8c7e0-8dcc-408b-958c-44c76514c577.png)

This model is expandable, but we can hard-code it to only Tier 1 Reviewers and Tier 2 Reviewers for now. @curtislisle mentioned that cyclical review is not a use case for Stanford, but it seems to be the norm for Kilian, since he mentioned that if a 2nd-level disagrees with the decision of a 1st-level, it should go back through review. Perhaps a boolean `cyclical_review` option on the Project could handle that logic?

**Comment by faiza-a** [comment]
Created this mockup ([Figma link](https://www.figma.com/file/2kHA8IlhMvxuWubSMdvmpm/User-Permissions-workflow?node-id=0%3A1)) for user workflow. Some similar things as Anne's mockups above. 

I am not sure about following but i included these options in mockups.

1. Super user can add more experiments to an existing projects (+ button next to experiment header).  Or does the import button do that?
2. Super user can edit email as well as tier/group of other users.
3. All users can view import export paths of project? but only super user can edit it.
4. All users can export the project? but only super user can import /delete it.
5. Super users will we be listed as collaborators in all projects by default? They can be included in members using '+' button to assign a review role by themselves or by other super users?

**Super User**
![Super User](https://user-images.githubusercontent.com/61198087/141017998-c25a2386-c6e5-4803-9f05-8b7a36ebc491.png)

**Other User**
![Other Users](https://user-images.githubusercontent.com/61198087/141012967-cca44956-e9d9-4209-a596-8f676fe9ee6b.png)

**Adding and editing users in Super User UI**
<img width="510" alt="Screen Shot 2021-11-09 at 5 16 28 PM" src="https://user-images.githubusercontent.com/61198087/141014008-4cbb06f8-069c-494a-8ffe-344248d43e75.png">

** Just another layout option**
![Another Layout Option](https://user-images.githubusercontent.com/61198087/141016311-f3ae6a91-1dda-41ea-9e51-2e40ffaec8a5.png)

**Comment by annehaley** [comment]
> * Super user can add more experiments to an existing projects (+ button next to experiment header).  Or does the import button do that?
> * Super user can edit email as well as tier/group of other users.
> * All users can view import export paths of project? but only super user can edit it.
> * All users can export the project? but only super user can import /delete it.
> * Super users will we be listed as collaborators in all projects by default? They can be included in members using '+' button to assign a review role by themselves or by other super users?

This looks perfect! I hadn't thought of 4 and 5. IIRC, your assumptions are valid. Although for 1, currently the import button performs the creation of experiments. It depends on if we want to implement that feature, but I think it would be a nice touch.  Could you also show us what the Experiment (and Project) creation form could look like? 

I also think that your idea of showing more information could be a nice feature and I do like that layout more.

**Comment by faiza-a** [comment]
> Could you also show us what the Experiment (and Project) creation form could look like?

Definitely. I will look at the feature and reach out for any questions :)
