### ISSUE TITLE
Automatic population of reviewer's comment box with NN results

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#208]
The control panel redesign concept included a feature wherein the results of an automatic evaluation from the server NN would automatically populate the reviewer's comment box so they could either agree or disagree with those results. However, this feature needs more planning and was therefore left out of the control panel redesign effort.

We need to consider the following: 

- What should the backend syntax for these comments on a ScanDecision be? How should we represent what features the user agrees are present? Should we include the percentage of confidence presented by the NN Evaluation? 
- How can we use this comment syntax to later feed back into the NN Model for continuous training?
- How should the UI design look for these tags, and how can we make it clear that a user can add additional commentary? Should the additional commentary go before or after the automatic evaluation representation?

**Comment by curtislisle** [comment]
In our discussion on 12/2/21, we started focusing on an additional field for the ScanDecision model to support other binary tags attached to scans.  The NN results agreed-on by the user could be stored here as well as annotation tags users apply to scans.  Adding a comment here to address this with this issue or another related issue to be created.
