### ISSUE TITLE
Window width & level widget redesign

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#214]
The UI widgets for window width and window level were greatly simplified in the control panel redesign, and we may need to reconsider the functionality needed for the user to review scans. Do the minimum and maximum values of the slider need to be mutable by the user? Should these values be set per frame or per scan?

**Comment by curtislisle** [comment]
After using MIQA a bit, I'd like to discuss a model extension.  When a user has adjusted the window & level until an image looks good, could MIQA save the window/level values with the scan so they are restored next time the scan is visited?  This might save a lot of time for clinicians revisiting scans.

**Comment by dzenanz** [comment]
Can this issue be closed now?

**Comment by annehaley** [comment]
This issue was made to keep note of some concerns raised after the control panel redesign. We haven't addressed some of these yet, so I think we should bring this up in a group discussion one more time before closing it.

**Comment by annehaley** [comment]
Kilian's main concern was keeping the width and level values consistent when flipping through frames in a scan

**Comment by annehaley** [comment]
Remaining changes to make:

1. Remove "Apply" button for presets, just auto apply when one is selected. This dropdown should also be disabled with the lock is active.
2. Replace the lock button with a dropdown that allows the user to lock the window settings: "Maintain for scan", "Maintain for experiment", or "Do not maintain". When the lock is dropped, the settings should auto adjust for the next image based off its range.
