### ISSUE TITLE
Consider alternate visualization for image artifacts

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#215]
Looking at this image, it is a bit odd that the top bar means "longer bar is good" while all the other bars mean "longer is bad". I think the color scheme is reversed on the top bar which makes sense, but I was wondering if we could make it more intuitive that they are inversely related.

One idea I had was to right-align the image artifact bars but keep the overall quality bar left-aligned. That would show them going a different way than quality, and would also align things mentally where things on the right are green/good and things on the left are red/bad.

![image](https://user-images.githubusercontent.com/81305/140397235-e7716a70-a763-486e-b459-bd2eb43b7d36.png)

**Comment by annehaley** [comment]
Okay, that's a good idea. It also makes me wonder which of these you want high numbers for and which you want low numbers for. Are all the numbers other than overall quality intended to be bad things that you want a low score on (in particular: full brain coverage)?

**Comment by annehaley** [comment]
Or, how ridiculous would it be if we reworded the bad things to their opposite and displayed `(1-value)*100`? For example "No lesions" would be 97%. That way the alignment of the bars and their coloration means the same thing for all values.

**Comment by dzenanz** [comment]
- Normal variants represents anatomical variation is neither good nor bad. Values itself are mostly false.
- Full brain coverage is mostly true, and we want it to be true. We could reverse this to be `incomplete brain coverage`.
- I plan to remove SNR and CNR from computations. As you didn't add them to visualization, it should be easy.
- We want everything else to be false, meaning lower is better.

**Comment by jeffbaumes** [comment]
I like the idea of turning everything into a positive ("no legions"), but it is slightly awkward to state the negation.

Another option is just to get rid of the bars for all the artifacts and put the numbers right next to them. Then the user is not trying to treat all the bars equally and uniformly (overall quality should be most important anyway). We could keep the color coding of the numbers though.

Overall as I think more about it I'm not convincing myself that this is a big enough issue to mess with much if at all right now. Reversed bars and negated names might be more confusing than they are worth.

**Comment by jeffbaumes** [comment]
I'm leaning toward trying putting everything as a positive with bars getting greener as they get longer. Everything would get negated except for "full brain coverage" and "normal variants". "Normal variants" could be represented as a gray/black color since it is neither good nor bad.
