### ISSUE TITLE
Figure out if we are vulnerable to email content injection

### ISSUE THREAD

**Issue by zachmullen** [OpenImaging/miqa#22]
We allow arbitrary content from clients to be set in the email fields. I'm not sure whether or not this is OK from a security standpoint; it will require a little bit of digging around.

**Comment by aashish24** [comment]
@zachmullen is this still relevant for the current version of MIQA?

**Comment by zachmullen** [comment]
This is certainly still a security concern (server-side email forgery) -- it means we must operate under the constraint that we trust all users of the system who have access to the email features.

I'll close this because it's not actionable.
