### ISSUE TITLE
Publish a short paper on MIQA

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#230]
https://2022.midl.io/call-for-papers.html

**Comment by aashish24** [comment]
MIDL22 suits us time-wise:

Full paper submission deadline 17 December 2021
Short paper submission deadline 22 April 2022

**Comment by dzenanz** [comment]
Tracked in GitHub at https://github.com/OpenImaging/MIDL2022ShortPaper and in [Overleaf](https://www.overleaf.com/project/625ee958e96b6c40d48ac3e9).

**Comment by annehaley** [comment]
Dzenan's paper was completed, submitted, and accepted:

> _We are delighted to inform you that your submission has been accepted as a short paper for the MIDL conference. Congratulations! You can find the final reviews for your paper on the submission's page on OpenReview._

^ Email from MIDL 2022 ([pc@2022.midl.io](mailto:pc@2022.midl.io))

**Comment by dzenanz** [comment]
Paper and its review are available: https://openreview.net/forum?id=dBxvjWJTVW-
