### ISSUE TITLE
Support option for Multiple scan decision choices 

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#242]
Our driving biological problem with Stanford only needs a single scan decision (usable, unusable, questionable) per scan.  However, if we add the ability to add multiple "tags" to a scan, MIQA could be useful for image annotation tasks.  This issue is to discuss if/ how we should incorporate multiple scan decisions into MIQA to support more future application areas with MIQA.

**Comment by curtislisle** [comment]
The current MIQA master requires a small code edit to change the scan decision choices, but once done, the system works very well.  The scan decision chips and addition of chips to notes works well for annotation applications.   

Question: should we make artifact_options something configurable through PUT api/configuration?  or just leave configurable through source code?

**Comment by zachmullen** [comment]
The standard way of doing these sorts of configurations or feature flags would be via an environment variable, which would be expressed in code within our `settings.py` file.  What is the code change that's necessary?

**Comment by curtislisle** [comment]
Thanks, Zach. It sounds like the application could look for an environment variable that overrides default behavior if and only if it is defined.  I like that way of doing configuration.  

the actual code change was in miqa/core/models/scan_decision.py:  MIQA imports the artifact definitions via  'import artifacts' from miqa.learning.nn_inference.  For my use case, I changed the implementation of default_identified_artifacts() to pull from a locally-defined list instead of from the list defined by the NN inference.

**Comment by annehaley** [comment]
The artifact selection chips added in #244 resolve this issue.
