### ISSUE TITLE
Scans downloads slower in production environment 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#254]
It does not happen in local deployments. We had observed the same behavior in very first version of MIQA (girder 3)

**Comment by aashish24** [comment]
Lets wait until Jim gets the latest version running on the same server as the Girder-3 version.

**Comment by annehaley** [comment]
@curtislisle noted that s3-stored files have much faster load times. Or, we could consider @thewtex's work on using zarr loading as resolving this issue (once it is complete).
