### ISSUE TITLE
Add ability to add crosshair location recorded during annotation of a scan 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#260]
similar to itk-snap suggested by @curtislisle for now we can just record mouse location and do the bbox implementation later

**Comment by curtislisle** [comment]
The location of the cursor (if it is saved) could be stored either in the notes or in a new field in the scan_decision model.  If we implemented a UI button with input text, it could append the current cursor position and description into a new attribute of the ScanDecision model called something like 'cursor_positions'. Then we might be able to implement a way to display the list and allow restoring the cursor to any previously saved positions by clicking the entry and its corresponding description.  Did this make any sense? :-)

**Comment by dzenanz** [comment]
We could add optional `cursor_location` to artifacts, so each artifact can have a physical position. We could then show chips with a position differently, e.g. the left end of a chip contains small cross-hairs icon which, when clicked, navigates the slice views to the recorded position.

**Comment by aashish24** [comment]
Updated the title as we decided to add the option to store bbox (multiple of those) in the future

**Comment by curtislisle** [comment]
In the tech meeting just now, we identified that saving the current position of the `crosshairs` in the scan decision model satisfies functionality desired for the annotation application of MIQA.  We do not need to map the user's mouse cursor to IJK or world space and save this.   Although we like it, we do not have a driving biological problem the requires the jumping-around functionality I demonstrated from `ITKSnap`. In reading previous comments from me on this thread, please globally replace the word cursor with crosshairs.  In `vi`, the appropriate command would be ` :.,$g/cursor/crosshairs/`  

 :-)
