### ISSUE TITLE
Support .nrrd files

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#262]
MIQA currently will not render `nrrd` files at all, even if the content is exactly the same as a `nifti` file that it can render.

**Comment by curtislisle** [comment]
I wonder if we just have some hard coded file type references to nifti
somewhere?  I expect  the ITK infrastructure is agnostic to reading .nrrd
vs .nii files, but this might not be the case.

**Comment by curtislisle** [comment]
if it isn't too much trouble while we are looking at acceptable image types: the Univ of Iowa images I have access to are in .mgz format.  This is the FreeSurfer format.  FreeSurfer is a popular tool in brain imaging work.  I will make a tiny example dataset for debugging and testing.

**Comment by dzenanz** [comment]
A [plugin for ITK](https://github.com/InsightSoftwareConsortium/itkMGHImageIO) already exists. I don't know whether it is enabled in `itk.js`, but enabling it shouldn't be hard if it isn't.

**Comment by curtislisle** [comment]
unfortunately, .mgz files aren't currently readable.  I received the following message for each import scan when running the import CSV.  We are currently using SimpleITK instead of itk during the reading operation:

```
 [2021-12-28 18:36:38,464: WARNING/ForkPoolWorker-1] .
celery_1    | [2021-12-28 18:36:38,464: WARNING/ForkPoolWorker-1] Error loading image with SimpleITK:
celery_1    | Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
celery_1    | sitk::ERROR: Unable to determine ImageIO reader for "/home/ftei-dsw/proj/miqa/predict-tiny/predict-demo/sub-001738_ses-24455_T1.mgz"
celery_1    | 
celery_1    | Trying NiBabel...
```

**Comment by curtislisle** [comment]
I am a bit confused about where to try and fix reading for FreeSurfer files.  It is in `core/conversion/nifti_to_zarr_ngff.py` where we use itk to convert from native image format to ZARR.  I see our development process pip installs `itk` and `itk-io` (which seems like the standard pack of readers).    We are using true ITK, not SimpleITK on the back end though, so I don't understand the error I received. 

On the client, 
`client/utils/registerReaders.js `seems to register only Nifti image reading clients.  But I would have expected ZARR to show up over here, if this is truly how we are reading the images on the client side.  

This isn't urgent, I was trying to be more helpful than just reporting "I got an error" .  I can hand convert a few images to Nifti for demonstration to Hans next month.  I'll bring this up in our meetings later.

**Comment by dzenanz** [comment]
If I remember correctly, we do not support zarr on the client yet. @thewtex is this correct?

**Comment by dzenanz** [comment]
@annehaley https://github.com/OpenImaging/miqa/blob/master/client/src/utils/registerReaders.js is probably where we need to add `.nrrd` to have it supported.

**Comment by dzenanz** [comment]
@curtislisle said he tried adding something to [registerReaders.js](https://github.com/OpenImaging/miqa/blob/master/client/src/utils/registerReaders.js) for `.mgz` without success. Are some additional steps needed @thewtex?

**Comment by thewtex** [comment]
In `registerReaders.js` it is only supporting Nifti -- explicit support is required there for `.mgz`, `.nrrd`.

Alternatively, we can move from `import vtkITKImageReader from 'vtk.js/Sources/IO/Misc/ITKImageReader';` to `itk-wasm` `readImageFlie`, which adds supports for all the files types directly.
