### ISSUE TITLE
Changes to project page design

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#273]
In our meeting with Stanford, we decided to make the following revisions to the project page design:
- color-code the bullets next to scan names according to the scan state (matching the donut colors) and add a tooltip to show the state as text
- Add an overall status next to project names in the project list, i.e. text like "(2/9)" with a tooltip like "2 of 9 scans complete"

**Comment by curtislisle** [comment]
I love the new summary visualization on the project page.  I have an issue, though: when a user performs an annotation and then goes back to the project page, the summary vis is not updated until the browser page is refreshed.  This could mislead someone about the actual number of scans still needing review if they forget to refresh.

**Comment by annehaley** [comment]
@curtislisle I failed to replicate this problem. When you made these `ScanDecision` objects, were you a tier 2 reviewer on the project or just a superuser? The `total_complete` scan count only includes scans whose last decision was made by someone with `tier_2_reviewer` permissions on the project.

**Comment by annehaley** [comment]
If this issue appears again @curtislisle, please file a separate issue for it. Closing this one now that its scope is complete.
