### ISSUE TITLE
Image zoom resets by itself

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#277]
Let's say the user has zoomed into one or more of MIQAs images, by using the right mouse button and dragging, during a review and then their mouse cursor accidentally brushes over the left side of the browser (showing the Experiment list, even if briefly).  The zooms of all axes views are restored to their original starting position.  If it isn't too hard to do, the zoom level of the images should be preserved unless the user refreshes the browser page, in my opinion.

**Comment by annehaley** [comment]
The problem is likely with [`fill2DView`](https://github.com/OpenImaging/miqa/blob/master/client/src/utils/fill2DView.js), or this would at least be the place to fix it. This function is called several times in the `VtkViewer` component, most notably in `onWindowResize`. We need to find some way to maintain the zoom level in this function.

**Comment by floryst** [comment]
You probably want some state to tell you if the camera was manually zoomed or not, as well as have a "reset" button that clears this state. That way, you can have `fill2DView` called only when the camera wasn't manually zoomed.

Determining if manual zoom occurred or not will depend on the InteractorStyle that you use, and whether that InteractorStyle exposes such information.

**Comment by annehaley** [comment]
@floryst I'm not sure if this information is what you were referring to, but `this.view.getInteractor().getClassName()` give us "vtkRenderWindowInteractor" and `this.view.getInteractor().getInteractorStyle().getClassName()` gives us "vtkInteractorStyleManipulator". Do either of these classes reveal manual zoom information?
