### ISSUE TITLE
Modify unique constraint on Frame `raw_path`

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#278]
@curtislisle attempted to make two of the same project (different names, same import path); Upon import, the second project failed to make any Frames because of the db constraint that no two Frame objects can have the same raw path.

The intent for this constraint is that no two Frames _in the same Project_ should have the same raw path, so we should modify that constraint accordingly. Additionally, the import function should have a more descriptive error when that constraint prevents the creation of Frame objects.

**Comment by zachmullen** [comment]
Check and unique constraints are only allowed to apply to a single relation (table). That's a limitation of the database itself.

It's perfectly fine to not be able to express all forms of data validation via DB integrity checks. We'll do the ones that are straightforward, and everything else can happen in python via `clean`. There are usually other ways to achieve ACID such as `select_for_update` plus a special column.

**Comment by annehaley** [comment]
> There are usually other ways to achieve ACID such as `select_for_update` plus a special column.

Could you elaborate on what you mean here?

If we can't add it as a DB integrity check, that means we can't have this checked in `Frame.objects.bulk_create()`. Do we really want to call `save` on each frame object in the list we import? This would mean n calls to the DB instead of 1. At that point, rather than use a model function and call it on every instance we create one-at-a-time, it would be more performant to put a check in our import's `evaluate_data` function (where we validate the format of the import file).

**Comment by annehaley** [comment]
After discussing this on a call, we decided that the Frame definition would be better off without any constraint on `raw_path` uniqueness. We should be able to consider the import csv as the ground truth, and there really is no consequence or unexpected behavior to prevent for two identical Frame objects existing.
