### ISSUE TITLE
Add Project setting to toggle between neurology and radiology orientations

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#279]
Currently, the definition of view orientations are hard-coded in the frontend as the expected axis orientations for neurology, so radiology scans appear flipped. We should add a toggle to the Project settings that can tell the `VtkViewer` which orientations to use.

**Comment by thewtex** [comment]
Also consider enabling vtk.js medical imaging rendering mode:

- https://www.kitware.com/vtk-js-v24-release-notes/
- https://github.com/Kitware/vtk-js/issues/1553
- https://github.com/Kitware/vtk-js/pull/2089
