### ISSUE TITLE
Make MIQA available on HTTPS publicly and setup continuous deployment 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#297]
Brandon and Bryon are the best resources on how to do it as they have done something similar for viame.kitware.com

**Comment by aashish24** [comment]
Brandon and Bryon are the best resources on how to do it as they have done something similar for viame.kitware.com

**Comment by annehaley** [comment]
Now available on `https://miqa.miqaweb.io/` thanks to @zachmullen
