### ISSUE TITLE
Make sessions expire

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#3]
The users have some requirement for very quick session timeouts (1 hour?).

**Comment by venkatabhishek** [comment]
To clarify, should the session timeout when the user has not performed any action on the front-end for the given time period or when the back-end has not received any requests from this user within this time period?

**Comment by dchiquito** [comment]
The consensus was that the default session timeout should be short (1 hour), and the client should refresh the token periodically as long as the user is active.

**Comment by venkatabhishek** [comment]
Latest agreed upon design:
1. When user is idle (i.e. no physical mouse movement, button clicks, etc.), for **15 minutes**, display popup
2. When user has not made any API calls (make decision, add note, etc.), for **30 minutes**, display popup
3. In both above cases, popup will automatically logout user in **2 minutes** and has 2 options:
    -  continue session (extend/refresh token)
    - logout (terminate session/token)
