### ISSUE TITLE
Basic integration of pixel-based NN classifier

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#31]
Integrate pixel based NN classifier into MIQA interface

**Comment by aashish24** [comment]
We will provide a single number on probability of good  or bad that can be displayed in the GUI

**Comment by aashish24** [comment]
* MIQA needs to deliver path to the file to the NN 
* Run the job async
* Compute the probabilities and send it to the MIQA server

**Comment by aashish24** [comment]
Closing this in favor of milestone
