### ISSUE TITLE
Allow scans without IQMs

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#32]
Ignore the scans without proper image quality metrics.

**Comment by dzenanz** [comment]
This will be important if/when we have a classifier which uses IQMs (image quality metrics).

**Comment by aashish24** [comment]
@dzenanz is this still relevant?

**Comment by dzenanz** [comment]
Yes, I think so.

**Comment by dzenanz** [comment]
Closing in favor of #444.
