### ISSUE TITLE
NN not running automatically in deployment

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#343]
There are no errors, but automatic evaluations are not present when reviewing the data. Happens on both SRI and Heroku instances.

**Comment by annehaley** [comment]
@zachmullen now that #360 is resolved, could you perform an import on the prod instance (I don't have permission) and post any celery output so we can identify the issue?

**Comment by annehaley** [comment]
We identified the issue that the `evaluate_data` task contains the following check:
```
if Path(frame.raw_path).exists():
```
This is not set up to support an s3 connection. @zachmullen suggests we download the file contents to a temporary directory before running the evaluation on them.

**Comment by annehaley** [comment]
@zachmullen resolved the issue and now evaluations are available on https://miqa.miqaweb.io/#/
