### ISSUE TITLE
Add Subjects to Experiments

### ISSUE THREAD

**Issue by annehaley** [OpenImaging/miqa#345]
In regards to a recent conversation with @curtislisle, these would probably be best represented with a new model in the system. The following fields should belong to the subject:

1. ID number
2. Sex
3. Age

**Comment by curtislisle** [comment]
We discussed that these attributes could be added to the Experiment as a
prototype to allow BIDS data to be loaded, but that these were really
"Subject" related data fields, not "experiment" fields, so it might be
motivation to have a subject model and a foreign key in the experiment
model record. Though Some datasets won't have subject information.  I'd
suggest we call the first one SubjectID or SubjectName (or whatever
convention we have for camel-casing model features.). This would be an
alphanumeric value for the subject's name or unique ID. This would allow
future expansion to have smart filtering through the API to only return
images of males, or of a particular subject

**Comment by annehaley** [comment]
#414 Includes the work from Curt and me; it adds subject_id to the scan (not the experiment).
