### ISSUE TITLE
Automatic evaluations not visible without edit access

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#367]
Is this intentional?

<img width="889" alt="Screenshot 2022-03-10 09 30 28" src="https://user-images.githubusercontent.com/1792121/157683791-facd3a5c-b5c7-471b-a9e1-d5c8c1668576.png">

**Comment by annehaley** [comment]
It was intentional but it was an arbitrary decision that can be changed. Should the display be the same, at the top right of the "locked" placeholder?

**Comment by dzenanz** [comment]
Yes, that is what I would have expected. Auto evaluations visible, but editing part locked out.
