### ISSUE TITLE
Get updated stanford data

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#38]

**Comment by aashish24** [comment]
I will get to it sooner, sorry for the delay

**Comment by dzenanz** [comment]
We might use this data for pre-training, see [self-supervised representation learning in MONAI v0.8](https://github.com/Project-MONAI/MONAI/blob/0.8.0/docs/source/whatsnew_0_8.md#self-supervised-representation-learning).

**Comment by dzenanz** [comment]
@aashish24 I would like to work on this next. After #289 is merged, I will do some experimentation to figure out proper influence on quality of each augmentation. But that involves a lot of waiting, having data would allow me to spend meaningful engineering time. Alternatively, I could focus on other projects for the next few weeks while you get the updated data.

**Comment by aashish24** [comment]
@dzenanz thanks for the reminder. I have put some of the data on the shared drive. Can you take a look? Another batch I will upload tonight.

**Comment by dzenanz** [comment]
I took a look. There are only 3 year follow-ups. I have some other stuff from before, baseline_v3 and year1_followup_v1. Also I am not sure that this is complete. This is only 38GB, whereas the other 2 are around 50GB each. And very important: please get the `unusable` folder, as that is the smallest and most interesting.
