### ISSUE TITLE
The size of emailed screenshots of the same image varies with browser window size

### ISSUE THREAD

**Issue by scottwittenburg** [OpenImaging/miqa#4]
From a user:

> It seems that the sizing of the attached snapshots for the same session vary in relationship to the client browser’s window size.  e.g. I’ve got a huge 4k display… if I maximize the browser and send screenshots, the resulting image attachments are very large.  However if I shrink the browser window down to ¼ of the display, I get much smaller attachments.  I would expect to get the same sized image irrespective of the browser window dimensions. Is there a way we can make this consistent irrespective of the browser size.

**Comment by aashish24** [comment]
I have created a new issue that clarifies the requirements (https://github.com/OpenImaging/miqa/issues/18). Closing this issue in favor of the new one.
