### ISSUE TITLE
Investigate error 400 when uploading scans through UI

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#426]
When trying to click the `Upload` button after selecting a `.nii.gz` file for upload, the server responded with a 400 from the `s3-upload` endpoint with no server logs. The problem persisted after running `docker-compose pull` and `docker-compose build`.

@hjmjohnson reported this issue when setting up the development environment.

**Comment by dchiquito** [comment]
I was unable to reproduce this locally. I think we will need to hop on another call to see the error in action.

**Comment by annehaley** [comment]
This hasn't popped up again, I believe this is fixed. Closing for now.
