### ISSUE TITLE
Generate Image Quality Metrics (IQMs)

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#444]
As this involves a non-trivial amount of computation, it should be done asynchronously.

We said we will make IQMs from [MRIQC](https://mriqc.readthedocs.io/en/stable/install.html#bare-metal-installation-only-python-3) available to reviewers.

**Comment by curtislisle** [comment]
One way to integrate MR QA algorithms is as additional models run asynchronously and automatically, the way @dzenanz's original model works.  Doing it this way shows off our learning model architecture, but means custom code to integrate a snapshod of standard QA algorithms into MIQA.  I am thinking that we might also want to explore the alternative approach of creating a script that uses the MIQA Client and makes calls to MRQC (or other existing QA code)  as more of a loosely-coupled solution.   I haven't explored coding this yet, but would like to talk about the alternatives in a future tech meeting.

**Comment by dzenanz** [comment]
Closing as a duplicate of #133.
