### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#45]
We need some more information before we can finish the export feature. If export is not being used in production, we can close this issue.

Originally Girder was storing multiple notes in a single text blob in this form: `JD (01/02/2020`): Taking note of this`. Apparently XNAT only has a single notes field with a character limit. We are storing notes in their own table, so converting to/from this format is non-trivial. 

Right now import is ignoring the notes field completely. Once we have information on the requirements around notes, we can finish import and implement export to complement it.

**Comment by annehaley** [comment]
This issue is outdated, and our import/export functionality is more fleshed out. Since #392 was merged, we can record the decisions made on scans in the csvs.
