### ISSUE TITLE
Check CSV columns/headers for global vs project specific import 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#453]

**Comment by aashish24** [comment]
* For project-specific import - every row should match the name of the project in the system. Currently, this is the behavior but we need to inform the user about the error message.

**Comment by aashish24** [comment]
"if the CSV file defines the project and you locally import that file into another project then the software does it" - is also reported

**Comment by aashish24** [comment]
"if the CSV file defines a project that does not exists, it states server no response"

**Comment by curtislisle** [comment]
On the current master as of 4/20/22 (commit xbce6), I tested imports.  The current behavior of importing a file into a single project ignores the project_name field.  Therefore, all rows of the CSV are imported into the current project regardless of what project_name was on the row.  This is different than I reported on our recent call.  I will send some example CSVs to Anne to discuss.
