### ISSUE TITLE
Export  failed but did not produce a meaning error 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#459]
We need steps to reproduce

**Comment by aashish24** [comment]
* Could it be related to permissions issues - where the user may not have the write permission on the export path

**Comment by aashish24** [comment]
With the latest release now it is desired to get a more meaningful error

**Comment by aashish24** [comment]
We will need to get specific error message from Stanford

**Comment by aashish24** [comment]
Related #474

**Comment by kipohl** [comment]
@jimklo can you provide that ?

**Comment by aashish24** [comment]
@jimklo any update on this one or can we close?
