### ISSUE TITLE
Require users to log in for all endpoints

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#46]
Should be simply adding a permission requirement to all of the ViewSets.

Setting import/export path should be an admin action.

**Comment by zachmullen** [comment]
I realize I'm a bit late to this party, but I think we should set DEFAULT_PERMISSION_CLASSES in our MiqaMixin config, overriding [this inherited default](https://github.com/girder/django-composed-configuration/blob/master/composed_configuration/_rest_framework.py#L75).
