### ISSUE TITLE
Automatic log out also does not seem to work in an expected manner 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#460]
- Logged out due to inactivity and then simply reloaded the image again is what reported

**Comment by zachmullen** [comment]
~~I just tested this locally and was unable to reproduce it. I also inspected the cookie values coming back and the code controlling it and couldn't see any reason why this would happen. If this is an issue, I'll need some steps to reproduce it at this point.~~

Actually I just hard-reloaded the page and noticed the actual issue, which was the opposite of what I had been looking for. I had expected that we were failing to log out from the server, but that's actually not the case. We are failing to remove the OAuth token from localStorage, which is still a valid authentication mechanism. We have to invalidate _both_.

I will put in a fix.
