### ISSUE TITLE
duplicate migrations just happened to the CSV format. Remove 0030_scan_subject_session.py

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#464]
When Anne and I pioneered adding subject and session information, we added session_ID and subject_ID in migration `0030_scan_subject_session.py`.  This was duplicated in a newer migration `0030_optional_scan_fields` except the fields are now subject_id and session_id.  I believe the original migration should now be removed as we don't need both versions of the fields.

**Comment by zachmullen** [comment]
I tested locally, and a `makemigrations --merge` seems to have worked fine.

**Comment by curtislisle** [comment]
I did a merge on my system, but then I noticed that it said it was expecting subject_id, session_id, subject_ID, and session_ID fields.  The fix migration commit just now didn't seem quite right, when I looked at the CSV fields file, but maybe I'm just confused...

**Comment by zachmullen** [comment]
I think Django was confused by the difference in case. I've got what I
believe is the correct fix now:

https://github.com/OpenImaging/miqa/pull/465

**Comment by annehaley** [comment]
Closed by #465
