### ISSUE TITLE
Verify production update instructions

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#469]
The last bit of the production README.md currently reads as follows:

# Updating the deployment
To non-destructively update your instance at any time:
1. Run `git lfs checkout <release_tag>`
2. Run `docker-compose pull`
3. Run `docker-compose build --pull --no-cache`
4. Run `docker-compose run --rm django ./manage.py migrate`
5. Run `docker-compose up -d`

Jim has reported that the build occurred, but was not applied to the existing production deployment. We need to test that these instructions work correctly and include a `docker-compose rm django` if they don't.

**Comment by aashish24** [comment]
* verify that instructions do not work - they don't destroy the last docker container and update after these steps 
* If not then insert a new docker-compose rm django step to correct it and verify if that works

**Comment by annehaley** [comment]
I was not able to replicate the problem; after running these commands, the container successfully updated both times I tried. Is anyone else able to get this problem to occur?
