### ISSUE TITLE
Multi-project import and export

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#472]
Add two new buttons on the interface, one for import one for export. When clicked, it would be equivalent to clicking import or export for each project the user has access to.

**Comment by annehaley** [comment]
We agreed that it is easier to allow all users access to the global import/export actions (whereas only a superuser may edit the global import/export paths). If this becomes a requested feature that each user has a different meaning of "global," we can implement something like this. For now, it would overcomplicate things.
