### ISSUE TITLE
keyboard shortcut Q not working

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#482]
After experimenting, I found that the w,s, and x keys advance the slices in each of the three axial displays, respectively. e,d, and c toggle full screen views of each corresponding view.  I expected q,a, and z to rewind the slices in each of the displays.  This works for the second (a) and third (Z) display, but the Q (for the first view?) doesn't do anything.  To match the other buttons, Q should decrease the slice in the Red/Axial window.

**Comment by annehaley** [comment]
I was not able to replicate this problem. @curtislisle is this issue still happening for you?

**Comment by curtislisle** [comment]
Yes, it still doesn’t work for me, but it isn’t that critical.  In the annotation system in AWS, the Q and W keys do not advance the red slice.  The other slice viewers (yellow & green) respond to their keys just fine.  Weird.

**Comment by annehaley** [comment]
Is there any further information you can provide that could help me identify the problem? I still cannot replicate this. Do any errors appear in the console when you attempt to use these keyboard shortcuts?
