### ISSUE TITLE
Session expiration does not seem to work as expected

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#485]
@jimklo could you provide steps to reproduce

**Comment by jimklo** [comment]
@aashish24 I'm not sure how reproducible this is however the steps I followed were:

1. ssh into miqa host server
2. sudo to git user
3. `git fetch --all`
4. `git checkout -b v0.0.10 tags/v0.0.10`
5. `git lfs pull`
6. `cd ./prod`
7. `docker-compose pull`
8. `docker-compose build --pull --no-cache`
9. `docker-compose run --rm django ./manage.py migrate`
10. `docker-compose up -d`
11. Open browser to `https://ncanda.sri.com/miqa2` - browser still logged in from last session from a week ago.

**Comment by zachmullen** [comment]
Ah, that makes total sense, thanks for these steps.

I think I just need to add another localStorage entry that records when the last login was, and check that value before we initiate the oauth flow.

**Comment by aashish24** [comment]
Thanks, @jimklo, for these steps. It sounds like @zachmullen has a good idea
