### ISSUE TITLE
Evaluate MONAI Label integration with MIQA 

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#488]

**Comment by dzenanz** [comment]
This only makes sense if we decide to add segmentation support to MIQA. And there are two kinds of integration possible:
 1. just using classifiers created by MONAI label and displaying results
 2. interactively improving segmentations in MIQA, thus improving underlying classifiers

Both options seem out of reach, given our current funding.

**Comment by dzenanz** [comment]
A video about Slicer + MONAI label: https://www.youtube.com/watch?v=wtiEe_jiUzg
