### ISSUE TITLE
Multiple logout clicks sometimes needed on demo site

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#498]
The miqa demo site seems to have an issue with logout which may be related to timing and maybe Heroku server warm-up? When I log in with the demo login button, this is the number of times I needed to click logout before actually being logged out: 2, 1, 3, 2, 1, 1, 1, 1. Unsure what the cause might be. This isn’t the most critical thing and could be a messy type of bug to deal with, but I just wanted to record my experience. Others should be able to replicate this but it’s definitely intermittent.

**Comment by zachmullen** [comment]
This is now deployed, and my few logout attempts have all worked the first try. @jeffbaumes could you test if it is fixed for you?
