### ISSUE TITLE
Forgot password button does not work

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#5]
On the login screen there is a "Forgot Password" button, shown outlined in red in the image.  When you click it nothing happens.

![forgot_password](https://user-images.githubusercontent.com/6527504/116148407-19091000-a69e-11eb-842b-7a34a4d2d000.png)

**Comment by jimklo** [comment]
This is functional in that it now links to the the Girder workflow.  Possibly a future enhancement would be to have a MIQA specific workflow that hides the Girder specific UI/workflow.

**Comment by aashish24** [comment]
Okay thanks, I will close this issue and create a new one with that specific request.
