### ISSUE TITLE
Project state cycling between correct and incorrect state

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#511]
When I created a new project on the demo instance, the project state started flashing between the current project and another project.

The following screen capture shows the switching (no user interaction was occurring):

![May-26-2022 13-28-18](https://user-images.githubusercontent.com/81305/170542846-790642c1-e75e-42e5-be5e-b26fe8e7fb72.gif)

**Comment by annehaley** [comment]
The attempted fix for this was this commit: https://github.com/OpenImaging/miqa/commit/6cd330a46f012414febd77b3273531221b2f637d. Did the bug still occur with a history that includes that commit?

**Comment by annehaley** [comment]
Resolved in https://github.com/OpenImaging/miqa/pull/514
