### ISSUE TITLE
Stale user browser tab authentication issue? 

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#513]
Lately when I have a stale MIQA front-end browser tab open, when I check it, I have been logged out.  That is good.  However, when I re-enter my credentials, I then receive a CSRF Forbidden error.  Refreshing the page didn't work for me (at least once), I believe. When I open a fresh tab instead, the login works. 
![Screen Shot 2022-05-27 at 11 12 33 AM](https://user-images.githubusercontent.com/2152950/170728606-78249fe8-0680-4c2b-b819-40c1553ac891.png)

**Comment by zachmullen** [comment]
That's interesting... Did you hit the back button, by chance?

**Comment by curtislisle** [comment]
I don't believe so.  I have generally been logging into the front and back end with the same admin login.  This was observed on the AWS production instance that is now behind the master branch.  I'll update code and observe if this ontinues to happen.

**Comment by curtislisle** [comment]
An update on this issue.  I still see this on master.  My use case might be unusual:  I am currently logging is as the superuser on both the server and client side.  Maybe this happens when the client browser is refreshed after my server side login expires?  This just happened on a debug=True instance, so we got more failure information: 


```
Reason given for failure:

    CSRF token missing or incorrect.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/3.2/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

Your browser is accepting cookies.
The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting. 
```

Simultaneously, the server logs:
   ```
        INFO     "GET /admin/jsi18n/ HTTP/1.1" 200 3195       basehttp.py:161
django_1    | [17:46:14] WARNING  Forbidden (CSRF token missing or incorrect.):     log.py:224
django_1    |                     /accounts/login/                                            
django_1    |            WARNING  "POST /accounts/login/ HTTP/1.1" 403 12533   basehttp.py:161
django_1    | [18:00:25] WARNING  Forbidden (CSRF token missing or incorrect.):     log.py:224
django_1    |                     /accounts/login/           
```                         
It seems the client is keeping an old token(?) state.  Refreshing the browser page doesn't work, but retyping the client URL (http://localhost:8081) in the same browser tab logs me back into MIQA without needing user/password.
