### ISSUE TITLE
[Hans] incrementally add scans to a project instead of having to reload entire project

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#526]
Is this already implemented or possible?  He suggested that MIQA could function as an "image repository" with persistent management of uploaded images.  Then as new scans are generated, they could be "added" to a project, instead of having to replace all scans each time.  

It is up to us, but he suggested that more of a persistent repository would be useful for his applications.

**Comment by annehaley** [comment]
It was possible before with the export/import flow, but the new miqa client makes this much easier to accomplish: https://pypi.org/project/miqa-python-client/
