### ISSUE TITLE
Restricted Python client for MIQA

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#528]
Try to keep scope small, but provide a way to upload and download scans and scan decisions from MIQA.  Provide a python module that could be used in a Jupyter notebook.  First, decide on which endpoints will be supported.  

Possible provide editing Scan Decisions (this could be a way to retrieve and possible edit multiple scan annotations)

**Comment by annehaley** [comment]
https://pypi.org/project/miqa-python-client/
