### ISSUE TITLE
[Hans] support NRRD format for imagery

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#542]
3D Slicer is transitioning toward increasing use of the NRRD format for imagery. It is supported well in Slicer's segmentation modules.  Consider allowing NRRD files as input for MIQA

**Comment by zachmullen** [comment]
I'd be happy to take on this feature if you want, @aashish24

**Comment by annehaley** [comment]
This is currently possible. You can add them just the same as any `.nii.gz` file, either in imports, via the miqa python client, or via the interface's "Add Scans" dialog.
