### ISSUE TITLE
Scan sorting

### ISSUE THREAD

**Issue by dzenanz** [OpenImaging/miqa#549]
Scan `10_` is displayed before scan `2_` ... `9_`. Should be after.

**Comment by zachmullen** [comment]
I think this is a wontfix. Scan names in our systems are opaque strings that come in via the import process, so we just sort them lexicographically. We don't impose any other semantics or constraints on the names.

My suggestion would be that users generating the data for import must ensure that the lexicographic ordering is the correct ordering, perhaps by padding the numbers with leading zeros.

**Comment by curtislisle** [comment]
I sympathize with Dženan, but I agree with not addressing this. When importing, I just fixed the names until I got the sorting I wanted. I have concerns any algorithm we add might have unintended consequences later.

**Comment by zachmullen** [comment]
FWIW, [postgres does support ICU / "natural" collation](https://www.postgresql.org/docs/current/collation.html), but it would be a significant amount of engineering to make sure that is installed and supported in all of our environments.

**Comment by dzenanz** [comment]
I added this because Kilian mentioned it on Slack.

**Comment by zachmullen** [comment]
I just ran a little experiment and postgres's out-of-the-box installed collation package can handle this. We'd need to run:

```sql
CREATE COLLATION numeric (provider = icu, locale = 'en@colNumeric=yes');
```

And use that collation for the column, which would just require a custom migration. I leave it up to the project leads to determine if it's worthwhile to introduce more advanced vendor-specific functionality like this.
