### ISSUE TITLE
Unused Computed mapMutations in ControlPanel Component

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#579]
In the `ControlPanel` component we have:

```ts
computed: {
 // ...
 ...mapMutations([
  'updateExperiment',
  'addScanDecision',
]),
```

However, these don't appear to be in use. Since we are using [direct-vuex](https://github.com/paroi-tech/direct-vuex) it seems we are able to access the mutations as methods on `store.commit`, e.g.:

```ts
const { updateExperiment } = store.commit;
const { addScanDecision } = store.commit;
```

In addition, the `...mapMutations` is found under `computed` whereas if they were in use we'd expect them to be under `methods`.

I figure they must be dead code from an earlier version? I'd like to remove them but also wanted to see if I am missing something here.

**Comment by annehaley** [comment]
Your initial instinct is correct, these are remnants from an earlier version. They can be removed.
