### ISSUE TITLE
Landing page: Adjust team member section

### ISSUE THREAD

**Issue by jeffbaumes** [OpenImaging/miqa#6]
From Curtis: One suggestion on this section might be to make the collaborator references into cards by adding an outline.  I say this because I think it is possible to mis-read the current layout between the top row and bottom row.  Alternatively, we could use the blue line only below the top row instead of between the logo and the person's detail.

**Comment by aashish24** [comment]
@jeffbaumes let us know if we can provide any help, it would be good if we can wrap up work on initial version of our website this month.

**Comment by jeffbaumes** [comment]
This change and others are now in the new `miqa-landing-page` repo. Among changes:

* Added NIH grant number
* Reordered collaborator list
* Fixed size of a few icons and logos
* Fixed button sizing issues
* Corrected capitalization of GitHub
* Added Vue.js as a tool we use and rearranged tools
* Faded hero animated image with blue to make text more readable

As soon as @brianhelba can help with pointing Netlify to the new repo, this will go live for review.
