### ISSUE TITLE
Unused `currentScan` watch in Scan.vue?

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#617]
In Scan.vue there is a watch on the `currentScan` getter:
```ts
    currentScan(scan) {
      if (scan) {
        // Gets the most recent scan decision
        const last = _.head(scan.decisions);
        // Returns null if no scan decision exists
        this.decision = last ? last.decision : null;
        this.decisionChanged = false;
        this.newNote = '';
      }
    },
```

But as far as I can tell it is never triggered (I've put a breakpoint on it and navigated between scans and it never hits).

I think this is because the Vuex getter is never mapped, e.g. `computed` has `...mapState` but there is no `currentScan` in it:
```ts
    ...mapState([
      'currentFrameId',
      'vtkViews',
      'frames',
      'scanFrames',
      'loadingFrame',
      'errorLoadingFrame',
    ]),
```

Wanted to confirm if my observation is correct?

**Comment by annehaley** [comment]
Absolutely correct. Nice catch. Changed in #631
