### ISSUE TITLE
Unused `reset` in Vuex Actions?

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#628]
The following action is in the Vuex store:
```ts
    reset({ state, commit }) {
      if (taskRunId >= 0) {
        state.workerPool.cancel(taskRunId);
        taskRunId = -1;
      }
      commit('reset');
      fileCache.clear();
      frameCache.clear();
    },
```

But doesn't appear to actually be used in MIQA. Instead there is an identically named function in `TimeoutDialog.vue`:
```ts
    const reset = async () => {
      await djangoRest.restoreLogin(store);
      djangoRest.projects();

      // reset dialog
      show.value = false;
      timeRemaining.value = 0;
      idleWarningTriggered.value = false;
      unauthorizedTriggered.value = false;
    };
```

It's perhaps also helpful to note that there is an identically named mutation in the Vuex store as well (this one is utilized):
```ts
    reset(state) {
      Object.assign(state, { ...state, ...initState });
    },
```

I ask for two reasons:

1. If it isn't utilized can it be eliminated?
2. There is some disparity between the actions taken by the store `reset` and the TimeoutDialog `reset`, specifically the TimeoutDialog `reset` does not:
 - Reset the `taskRunId` used by the `workerPool`
 - Cancel existing jobs in the `workerPool`
 - Clear the `fileCache` or `frameCache`
 
And I suspect the above may be something we'd want the code in TimeoutDialog to be doing?

Or am I misunderstanding how this works? Thanks!

**Comment by annehaley** [comment]
You're right that we don't call the action currently. I put in #631 to add that dispatched action when we load the app.

The reset function in `TimeoutDialog` is pretty much unrelated; it is scoped to reset the state of that component and refresh the login so that the user may choose to continue their session. The vuex reset functions are scoped to handle the state of the whole app.
