### ISSUE TITLE
Support multi-users in MIQA with permissions

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#71]
Currently we have one user, we need to support multi-user mode where each user will have their own session and may import their own CSV 

* A user has multiple sessions to review
* A session may have only one user with write access and others may have read access (have a lock on the session)
* There is no need for concurrent editing
* Each user has equal rights to write access on any imported session as long as they have write permission
* For now, any user can unlock the session but will be prompted 
* We should be able to see who owns the lock

**Comment by aashish24** [comment]
* A user may have their own session but can be part of multiple sessions 
* A session may have only one user with write access and others may have read access (have a lock on the session)
*

**Comment by aashish24** [comment]
Relates to #72

**Comment by aashish24** [comment]
The workflow  and the features will be:

* Users are linked to a particular site
* Define various kinds of users (roles) of the system: admin (site exemption), supervisor (PI, assigns tasks, per site), reviewer (review on site, they assigned a site), technician (user of MIQA from remote site - they can upload and they can look at review results, write access to the data from their site only) 
* On import, the session will be only visible to supervisor

**Comment by annehaley** [comment]
Here is a concept diagram for new model relationships to create a more user-centric MIQA:
![User-centric MIQA drawio](https://user-images.githubusercontent.com/44912689/133638640-c368e00b-c14c-425c-a61a-bb0439e85e33.png)

(Open for revision)

**Comment by annehaley** [comment]
Relates to #122
