### ISSUE TITLE
Add Documentation to GitHub Wiki

### ISSUE THREAD

**Issue by curtislisle** [OpenImaging/miqa#8]
It was mentioned on 5/12/21 that keeping a MIQA system description and use case workflows in the Github wiki would help newcomers to the project.  

This issue is about building out the MIQA Wiki to be a more complete description and 'go to' location for system documentation

**Comment by annehaley** [comment]
This can be considered resolved with #433, we now have a designated website for documentation at https://openimaging.github.io/miqa/
