### ISSUE TITLE
Support loading data directly into MIQA (client side rendering, no data loading to server)

### ISSUE THREAD

**Issue by aashish24** [OpenImaging/miqa#87]

**Comment by aashish24** [comment]
@annehaley would you like to take this one?

**Comment by aashish24** [comment]
* We could ask for meta-information  about project, ids and others during the import

**Comment by dzenanz** [comment]
I remember that @scottwittenburg started work on this in the old version. But I can't find that WIP branch now.

**Comment by aashish24** [comment]
For now: 

1. User uploads a bunch of files to MIQA server 
2. MIQA creates a default project with the unknown project and unknown experiment

**Comment by jeffbaumes** [comment]
I believe this is the solution we discussed implementing today, at least very roughly.

![image](https://user-images.githubusercontent.com/81305/152425550-d5020359-bed0-4636-9708-926d126d7446.png)

**Comment by annehaley** [comment]
Closed with #318
