### ISSUE TITLE
Verify email login takes you to http://django/, not the web app

### ISSUE THREAD

**Issue by dchiquito** [OpenImaging/miqa#92]
After verifying your email, you get taken to the root of the django app, not back to the web app. This should happen automatically.

**Comment by zachmullen** [comment]
I think this just requires setting a configuration setting.

**Comment by zachmullen** [comment]
Alternatively, if the django app doesn't have any home page, we can do [what we did on dkc-next](https://github.com/girder/dkc-next/blob/916c511f7ee0cb848e4dd5749ee4bd6e5d549165/dkc/urls.py#L26)

**Comment by dchiquito** [comment]
This is actually a much larger bug: https://github.com/OpenImaging/miqa/issues/94

**Comment by dchiquito** [comment]
I got my issues mixed up, this is actually fixed in https://github.com/OpenImaging/miqa/pull/95/commits/6cb033ccd61b5c034f9127ba3b2908e347308633
